version: "3.7"

services:
  app:
    container_name: movies-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - movies-db
    links:
      - movies-db
    restart: unless-stopped
    volumes:
      - ./:/app
    env_file: .env
    environment:
      - PORT=$PORT
      - DB_NAME=$DB_NAME
      - DB_COLLECTION=$DB_COLLECTION
      - DB_CONNECTION=$DB_CONNECTION
      - WHITELIST_URL1=$WHITELIST_URL1
      - WHITELIST_URL2=$WHITELIST_URL2
    ports:
      - 4000:4000

  movies-db:
    container_name: movies-db
    image: mongo:latest
    restart: unless-stopped
    volumes:     
      - dbdata:/data/db
    ports:
      - 27017:27017

volumes:
  dbdata: